In [34]:
import pandas as pd
import numpy as np
import plotly.express as px

In [35]:
df_obese = pd.read_csv('./data/share-of-adults-defined-as-obese.csv')
df_cost_healty = pd.read_csv('./data/cost-healthy-diet.csv')
df_gdp_percapita = pd.read_csv('./data/gdp-per-capita-worldbank.csv')
df_population = pd.read_csv('./data/pop_proj.csv')

In [65]:
df_obese

      index       Entity Code  Year       bmi
0        27  Afghanistan  AFG  2017  12.83908
1        28  Afghanistan  AFG  2018  13.72347
2        29  Afghanistan  AFG  2019  14.64141
3        30  Afghanistan  AFG  2020  15.59125
4        31  Afghanistan  AFG  2021  16.57636
...     ...          ...  ...   ...       ...
1231   6793     Zimbabwe  ZWE  2018  10.68571
1232   6794     Zimbabwe  ZWE  2019  11.10584
1233   6795     Zimbabwe  ZWE  2020  11.53326
1234   6796     Zimbabwe  ZWE  2021  11.97260
1235   6797     Zimbabwe  ZWE  2022  12.42700

[1236 rows x 5 columns]

In [36]:
df_cost_healty

        Entity Code  Year  Cost of a healthy diet
0      Albania  ALB  2017                    3.04
1      Albania  ALB  2018                    3.13
2      Albania  ALB  2019                    3.32
3      Albania  ALB  2020                    3.40
4      Albania  ALB  2021                    3.49
...        ...  ...   ...                     ...
1485    Zambia  ZMB  2021                    3.28
1486    Zambia  ZMB  2022                    3.61
1487    Zambia  ZMB  2023                    3.81
1488    Zambia  ZMB  2024                    3.99
1489  Zimbabwe  ZWE  2017                    3.54

[1490 rows x 4 columns]

In [37]:
df_gdp_percapita

,Entity,Code,Year,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID
0,Afghanistan,AFG,2000,1617.8264,NaN
1,Afghanistan,AFG,2001,1454.1108,NaN
2,Afghanistan,AFG,2002,1774.3087,NaN
3,Afghanistan,AFG,2003,1815.9282,NaN
4,Afghanistan,AFG,2004,1776.9182,NaN
...,...,...,...,...,...
7306,Zimbabwe,ZWE,2020,2987.2683,NaN
7307,Zimbabwe,ZWE,2021,3184.7847,NaN
7308,Zimbabwe,ZWE,2022,3323.1184,NaN
7309,Zimbabwe,ZWE,2023,3442.2488,Africa
7310,Zimbabwe,ZWE,2024,3450.1296,NaN

In [38]:
df_gdp_percapita= df_gdp_percapita[df_gdp_percapita['Year']>=2017]
df_gdp_percapita = df_gdp_percapita.reset_index()
df_gdp_percapita

,index,Entity,Code,Year,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID
0,17,Afghanistan,AFG,2017,2952.9990,NaN
1,18,Afghanistan,AFG,2018,2902.3920,NaN
2,19,Afghanistan,AFG,2019,2927.2450,NaN
3,20,Afghanistan,AFG,2020,2769.6858,NaN
4,21,Afghanistan,AFG,2021,2144.1665,NaN
...,...,...,...,...,...,...
1749,7306,Zimbabwe,ZWE,2020,2987.2683,NaN
1750,7307,Zimbabwe,ZWE,2021,3184.7847,NaN
1751,7308,Zimbabwe,ZWE,2022,3323.1184,NaN
1752,7309,Zimbabwe,ZWE,2023,3442.2488,Africa
1753,7310,Zimbabwe,ZWE,2024,3450.1296,NaN

In [39]:
df_gdp_percapita = df_gdp_percapita.drop(['World regions according to OWID','Code','index'],axis =1)

In [40]:
df_gdp_percapita = df_gdp_percapita.rename(columns= {'GDP per capita, PPP (constant 2021 international $)':'gdp'})
df_gdp_percapita

           Entity  Year        gdp
0     Afghanistan  2017  2952.9990
1     Afghanistan  2018  2902.3920
2     Afghanistan  2019  2927.2450
3     Afghanistan  2020  2769.6858
4     Afghanistan  2021  2144.1665
...           ...   ...        ...
1749     Zimbabwe  2020  2987.2683
1750     Zimbabwe  2021  3184.7847
1751     Zimbabwe  2022  3323.1184
1752     Zimbabwe  2023  3442.2488
1753     Zimbabwe  2024  3450.1296

[1754 rows x 3 columns]

In [41]:
df_obese = df_obese[df_obese['Year']>=2017]
df_obese = df_obese.reset_index()

In [42]:
df_cost_healty.Year.unique()

array([2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [43]:
df_obese.columns

Index(['index', 'Entity', 'Code', 'Year',
       'Prevalence of obesity among adults, BMI >= 30 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age'],
      dtype='object')

In [44]:
df_obese_vs_cost = df_obese[df_obese['Entity'] != 'World']
df = pd.merge(df_cost_healty,df_obese,on = ['Year','Entity'], how = 'right')
df = pd.merge(df_cost_healty,df_gdp_percapita,on = ['Year','Entity'], how = 'right')
df = df.dropna()
df = df.reset_index(drop = True)
#df = df.drop(['Code_x','index','Code_y'],axis = 1)
df = df.rename(columns = {'Prevalence of obesity among adults, BMI >= 30 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age': '% of obese adults'})
df

        Entity Code  Year  Cost of a healthy diet         gdp
0      Albania  ALB  2017                    3.04  14155.0400
1      Albania  ALB  2018                    3.13  14710.9820
2      Albania  ALB  2019                    3.32  15078.5070
3      Albania  ALB  2020                    3.40  14662.7960
4      Albania  ALB  2021                    3.49  16126.7770
...        ...  ...   ...                     ...         ...
1357    Zambia  ZMB  2021                    3.28   3503.0350
1358    Zambia  ZMB  2022                    3.61   3585.1238
1359    Zambia  ZMB  2023                    3.81   3673.4841
1360    Zambia  ZMB  2024                    3.99   3716.0374
1361  Zimbabwe  ZWE  2017                    3.54   3453.5059

[1362 rows x 5 columns]

In [45]:
df_population = df_population[df_population['Year']>=2017]
df_population = df_population[df_population['Year']<=2024]
df_population.columns

Index(['Entity', 'Code', 'Year',
       'Population - Sex: all - Age: all - Variant: estimates',
       'Population - Sex: all - Age: all - Variant: medium'],
      dtype='object')

In [46]:
df_population = df_population.drop('Population - Sex: all - Age: all - Variant: medium',axis=1)
df_population = df_population.drop('Code',axis=1)
df_population = df_population.rename(columns={'Population - Sex: all - Age: all - Variant: estimates':'population'})

In [47]:
df_population = df_population.reset_index(drop = True)
df_population

           Entity  Year  population
0     Afghanistan  2017  35688941.0
1     Afghanistan  2018  36743040.0
2     Afghanistan  2019  37856125.0
3     Afghanistan  2020  39068977.0
4     Afghanistan  2021  40000410.0
...           ...   ...         ...
2043     Zimbabwe  2020  15526887.0
2044     Zimbabwe  2021  15797220.0
2045     Zimbabwe  2022  16069061.0
2046     Zimbabwe  2023  16340829.0
2047     Zimbabwe  2024         NaN

[2048 rows x 3 columns]

In [48]:
df_population.isna().sum()

Entity          0
Year            0
population    256
dtype: int64

In [49]:
df = df.drop('Code',axis=1)

In [50]:
df_merged = pd.merge(df,df_population, on = ['Year','Entity'], how = 'right')
df_merged

           Entity  Year  Cost of a healthy diet  gdp  population
0     Afghanistan  2017                     NaN  NaN  35688941.0
1     Afghanistan  2018                     NaN  NaN  36743040.0
2     Afghanistan  2019                     NaN  NaN  37856125.0
3     Afghanistan  2020                     NaN  NaN  39068977.0
4     Afghanistan  2021                     NaN  NaN  40000410.0
...           ...   ...                     ...  ...         ...
2043     Zimbabwe  2020                     NaN  NaN  15526887.0
2044     Zimbabwe  2021                     NaN  NaN  15797220.0
2045     Zimbabwe  2022                     NaN  NaN  16069061.0
2046     Zimbabwe  2023                     NaN  NaN  16340829.0
2047     Zimbabwe  2024                     NaN  NaN         NaN

[2048 rows x 5 columns]

In [51]:
df_merged = df_merged.dropna()

In [52]:
df_merged.shape

(1199, 5)

In [53]:
df_merged = df_merged.reset_index(drop=True)
df_merged

        Entity  Year  Cost of a healthy diet         gdp  population
0      Albania  2017                    3.04  14155.0400   2898245.0
1      Albania  2018                    3.13  14710.9820   2894229.0
2      Albania  2019                    3.32  15078.5070   2885011.0
3      Albania  2020                    3.40  14662.7960   2871950.0
4      Albania  2021                    3.49  16126.7770   2849641.0
...        ...   ...                     ...         ...         ...
1194    Zambia  2020                    2.96   3391.5955  19059394.0
1195    Zambia  2021                    3.28   3503.0350  19603610.0
1196    Zambia  2022                    3.61   3585.1238  20152935.0
1197    Zambia  2023                    3.81   3673.4841  20723967.0
1198  Zimbabwe  2017                    3.54   3453.5059  14812484.0

[1199 rows x 5 columns]

In [54]:
df_merged["population"] = df_merged["population"].astype(int)
df_merged

        Entity  Year  Cost of a healthy diet         gdp  population
0      Albania  2017                    3.04  14155.0400     2898245
1      Albania  2018                    3.13  14710.9820     2894229
2      Albania  2019                    3.32  15078.5070     2885011
3      Albania  2020                    3.40  14662.7960     2871950
4      Albania  2021                    3.49  16126.7770     2849641
...        ...   ...                     ...         ...         ...
1194    Zambia  2020                    2.96   3391.5955    19059394
1195    Zambia  2021                    3.28   3503.0350    19603610
1196    Zambia  2022                    3.61   3585.1238    20152935
1197    Zambia  2023                    3.81   3673.4841    20723967
1198  Zimbabwe  2017                    3.54   3453.5059    14812484

[1199 rows x 5 columns]

In [55]:
continent_mapping = {
    # Individual Countries
    
    # Europe
    'Albania': 'Europe', 'ALB': 'Europe',
    'Armenia': 'Europe', 'ARM': 'Europe',
    'Austria': 'Europe', 'AUT': 'Europe',
    'Belarus': 'Europe', 'BLR': 'Europe',
    'Belgium': 'Europe', 'BEL': 'Europe',
    'Bosnia and Herzegovina': 'Europe', 'BIH': 'Europe',
    'Bulgaria': 'Europe', 'BGR': 'Europe',
    'Croatia': 'Europe', 'HRV': 'Europe',
    'Cyprus': 'Europe', 'CYP': 'Europe',
    'Czechia': 'Europe', 'CZE': 'Europe',
    'Denmark': 'Europe', 'DNK': 'Europe',
    'Estonia': 'Europe', 'EST': 'Europe',
    'Finland': 'Europe', 'FIN': 'Europe',
    'France': 'Europe', 'FRA': 'Europe',
    'Germany': 'Europe', 'DEU': 'Europe',
    'Greece': 'Europe', 'GRC': 'Europe',
    'Hungary': 'Europe', 'HUN': 'Europe',
    'Iceland': 'Europe', 'ISL': 'Europe',
    'Ireland': 'Europe', 'IRL': 'Europe',
    'Italy': 'Europe', 'ITA': 'Europe',
    'Latvia': 'Europe', 'LVA': 'Europe',
    'Lithuania': 'Europe', 'LTU': 'Europe',
    'Luxembourg': 'Europe', 'LUX': 'Europe',
    'Malta': 'Europe', 'MLT': 'Europe',
    'Moldova': 'Europe', 'MDA': 'Europe',
    'Montenegro': 'Europe', 'MNE': 'Europe',
    'Netherlands': 'Europe', 'NLD': 'Europe',
    'North Macedonia': 'Europe', 'MKD': 'Europe',
    'Norway': 'Europe', 'NOR': 'Europe',
    'Poland': 'Europe', 'POL': 'Europe',
    'Portugal': 'Europe', 'PRT': 'Europe',
    'Romania': 'Europe', 'ROU': 'Europe',
    'Russia': 'Europe', 'RUS': 'Europe',
    'Serbia': 'Europe', 'SRB': 'Europe',
    'Slovakia': 'Europe', 'SVK': 'Europe',
    'Slovenia': 'Europe', 'SVN': 'Europe',
    'Spain': 'Europe', 'ESP': 'Europe',
    'Sweden': 'Europe', 'SWE': 'Europe',
    'Switzerland': 'Europe', 'CHE': 'Europe',
    'Turkey': 'Europe/Asia', 'TUR': 'Asia',  # Transcontinental
    'Ukraine': 'Europe', 'UKR': 'Europe',
    'United Kingdom': 'Europe', 'GBR': 'Europe',
    
    # Asia
    'Azerbaijan': 'Asia', 'AZE': 'Asia',
    'Bahrain': 'Asia', 'BHR': 'Asia',
    'Bangladesh': 'Asia', 'BGD': 'Asia',
    'Bhutan': 'Asia', 'BTN': 'Asia',
    'Brunei': 'Asia', 'BRN': 'Asia',
    'Cambodia': 'Asia', 'KHM': 'Asia',
    'China': 'Asia', 'CHN': 'Asia',
    'Georgia': 'Asia', 'GEO': 'Asia',
    'Hong Kong': 'Asia', 'HKG': 'Asia',
    'India': 'Asia', 'IND': 'Asia',
    'Indonesia': 'Asia', 'IDN': 'Asia',
    'Iran': 'Asia', 'IRN': 'Asia',
    'Iraq': 'Asia', 'IRQ': 'Asia',
    'Israel': 'Asia', 'ISR': 'Asia',
    'Japan': 'Asia', 'JPN': 'Asia',
    'Jordan': 'Asia', 'JOR': 'Asia',
    'Kazakhstan': 'Asia', 'KAZ': 'Asia',
    'Kuwait': 'Asia', 'KWT': 'Asia',
    'Kyrgyzstan': 'Asia', 'KGZ': 'Asia',
    'Laos': 'Asia', 'LAO': 'Asia',
    'Lebanon': 'Asia', 'LBN': 'Asia',
    'Malaysia': 'Asia', 'MYS': 'Asia',
    'Maldives': 'Asia', 'MDV': 'Asia',
    'Mongolia': 'Asia', 'MNG': 'Asia',
    'Myanmar': 'Asia', 'MMR': 'Asia',
    'Nepal': 'Asia', 'NPL': 'Asia',
    'North Korea': 'Asia', 'PRK': 'Asia',
    'Oman': 'Asia', 'OMN': 'Asia',
    'Pakistan': 'Asia', 'PAK': 'Asia',
    'Palestine': 'Asia', 'PSE': 'Asia',
    'Philippines': 'Asia', 'PHL': 'Asia',
    'Qatar': 'Asia', 'QAT': 'Asia',
    'Saudi Arabia': 'Asia', 'SAU': 'Asia',
    'Singapore': 'Asia', 'SGP': 'Asia',
    'South Korea': 'Asia', 'KOR': 'Asia',
    'Sri Lanka': 'Asia', 'LKA': 'Asia',
    'Syria': 'Asia', 'SYR': 'Asia',
    'Taiwan': 'Asia', 'TWN': 'Asia',
    'Tajikistan': 'Asia', 'TJK': 'Asia',
    'Thailand': 'Asia', 'THA': 'Asia',
    'Turkmenistan': 'Asia', 'TKM': 'Asia',
    'United Arab Emirates': 'Asia', 'ARE': 'Asia',
    'Uzbekistan': 'Asia', 'UZB': 'Asia',
    'Vietnam': 'Asia', 'VNM': 'Asia',
    'Yemen': 'Asia', 'YEM': 'Asia',
    
    # Africa
    'Algeria': 'Africa', 'DZA': 'Africa',
    'Angola': 'Africa', 'AGO': 'Africa',
    'Benin': 'Africa', 'BEN': 'Africa',
    'Botswana': 'Africa', 'BWA': 'Africa',
    'Burkina Faso': 'Africa', 'BFA': 'Africa',
    'Burundi': 'Africa', 'BDI': 'Africa',
    'Cameroon': 'Africa', 'CMR': 'Africa',
    'Cape Verde': 'Africa', 'CPV': 'Africa',
    'Central African Republic': 'Africa', 'CAF': 'Africa',
    'Chad': 'Africa', 'TCD': 'Africa',
    'Comoros': 'Africa', 'COM': 'Africa',
    'Congo': 'Africa', 'COG': 'Africa',
    'Cote d\'Ivoire': 'Africa', 'CIV': 'Africa',
    'Democratic Republic of Congo': 'Africa', 'COD': 'Africa',
    'Djibouti': 'Africa', 'DJI': 'Africa',
    'Egypt': 'Africa', 'EGY': 'Africa',
    'Equatorial Guinea': 'Africa', 'GNQ': 'Africa',
    'Eritrea': 'Africa', 'ERI': 'Africa',
    'Eswatini': 'Africa', 'SWZ': 'Africa',
    'Ethiopia': 'Africa', 'ETH': 'Africa',
    'Gabon': 'Africa', 'GAB': 'Africa',
    'Gambia': 'Africa', 'GMB': 'Africa',
    'Ghana': 'Africa', 'GHA': 'Africa',
    'Guinea': 'Africa', 'GIN': 'Africa',
    'Guinea-Bissau': 'Africa', 'GNB': 'Africa',
    'Kenya': 'Africa', 'KEN': 'Africa',
    'Lesotho': 'Africa', 'LSO': 'Africa',
    'Liberia': 'Africa', 'LBR': 'Africa',
    'Libya': 'Africa', 'LBY': 'Africa',
    'Madagascar': 'Africa', 'MDG': 'Africa',
    'Malawi': 'Africa', 'MWI': 'Africa',
    'Mali': 'Africa', 'MLI': 'Africa',
    'Mauritania': 'Africa', 'MRT': 'Africa',
    'Mauritius': 'Africa', 'MUS': 'Africa',
    'Morocco': 'Africa', 'MAR': 'Africa',
    'Mozambique': 'Africa', 'MOZ': 'Africa',
    'Namibia': 'Africa', 'NAM': 'Africa',
    'Niger': 'Africa', 'NER': 'Africa',
    'Nigeria': 'Africa', 'NGA': 'Africa',
    'Rwanda': 'Africa', 'RWA': 'Africa',
    'Sao Tome and Principe': 'Africa', 'STP': 'Africa',
    'Senegal': 'Africa', 'SEN': 'Africa',
    'Seychelles': 'Africa', 'SYC': 'Africa',
    'Sierra Leone': 'Africa', 'SLE': 'Africa',
    'Somalia': 'Africa', 'SOM': 'Africa',
    'South Africa': 'Africa', 'ZAF': 'Africa',
    'South Sudan': 'Africa', 'SSD': 'Africa',
    'Sudan': 'Africa', 'SDN': 'Africa',
    'Tanzania': 'Africa', 'TZA': 'Africa',
    'Togo': 'Africa', 'TGO': 'Africa',
    'Tunisia': 'Africa', 'TUN': 'Africa',
    'Uganda': 'Africa', 'UGA': 'Africa',
    'Zambia': 'Africa', 'ZMB': 'Africa',
    'Zimbabwe': 'Africa', 'ZWE': 'Africa',
    
    # North America
    'Antigua and Barbuda': 'North America', 'ATG': 'North America',
    'Bahamas': 'North America', 'BHS': 'North America',
    'Barbados': 'North America', 'BRB': 'North America',
    'Belize': 'North America', 'BLZ': 'North America',
    'Bermuda': 'North America', 'BMU': 'North America',
    'Canada': 'North America', 'CAN': 'North America',
    'Costa Rica': 'North America', 'CRI': 'North America',
    'Cuba': 'North America', 'CUB': 'North America',
    'Dominica': 'North America', 'DMA': 'North America',
    'Dominican Republic': 'North America', 'DOM': 'North America',
    'El Salvador': 'North America', 'SLV': 'North America',
    'Grenada': 'North America', 'GRD': 'North America',
    'Guatemala': 'North America', 'GTM': 'North America',
    'Haiti': 'North America', 'HTI': 'North America',
    'Honduras': 'North America', 'HND': 'North America',
    'Jamaica': 'North America', 'JAM': 'North America',
    'Mexico': 'North America', 'MEX': 'North America',
    'Nicaragua': 'North America', 'NIC': 'North America',
    'Panama': 'North America', 'PAN': 'North America',
    'Saint Kitts and Nevis': 'North America', 'KNA': 'North America',
    'Saint Lucia': 'North America', 'LCA': 'North America',
    'Saint Vincent and the Grenadines': 'North America', 'VCT': 'North America',
    'Trinidad and Tobago': 'North America', 'TTO': 'North America',
    'United States': 'North America', 'USA': 'North America',
    
    # South America
    'Argentina': 'South America', 'ARG': 'South America',
    'Bolivia': 'South America', 'BOL': 'South America',
    'Brazil': 'South America', 'BRA': 'South America',
    'Chile': 'South America', 'CHL': 'South America',
    'Colombia': 'South America', 'COL': 'South America',
    'Ecuador': 'South America', 'ECU': 'South America',
    'Guyana': 'South America', 'GUY': 'South America',
    'Paraguay': 'South America', 'PRY': 'South America',
    'Peru': 'South America', 'PER': 'South America',
    'Suriname': 'South America', 'SUR': 'South America',
    'Uruguay': 'South America', 'URY': 'South America',
    'Venezuela': 'South America', 'VEN': 'South America',
    
    # Oceania
    'Australia': 'Oceania', 'AUS': 'Oceania',
    'Fiji': 'Oceania', 'FJI': 'Oceania',
    'Kiribati': 'Oceania', 'KIR': 'Oceania',
    'Marshall Islands': 'Oceania', 'MHL': 'Oceania',
    'Micronesia': 'Oceania', 'FSM': 'Oceania',
    'Nauru': 'Oceania', 'NRU': 'Oceania',
    'New Zealand': 'Oceania', 'NZL': 'Oceania',
    'Palau': 'Oceania', 'PLW': 'Oceania',
    'Papua New Guinea': 'Oceania', 'PNG': 'Oceania',
    'Samoa': 'Oceania', 'WSM': 'Oceania',
    'Solomon Islands': 'Oceania', 'SLB': 'Oceania',
    'Tonga': 'Oceania', 'TON': 'Oceania',
    'Tuvalu': 'Oceania', 'TUV': 'Oceania',
    'Vanuatu': 'Oceania', 'VUT': 'Oceania',
    
    # Caribbean Islands (could be grouped with North America or separately)
    'Aruba': 'North America', 'ABW': 'North America',
    'British Virgin Islands': 'North America', 'VGB': 'North America',
    'Cayman Islands': 'North America', 'CYM': 'North America',
    'Curacao': 'North America', 'CUW': 'North America',
    
    # Regional Groupings from your dataset
    'East Asia and Pacific (WB)': 'East Asia & Pacific Region',
    'Europe and Central Asia (WB)': 'Europe & Central Asia Region',
    'High-income countries': 'High Income Group',
    'Latin America and Caribbean (WB)': 'Latin America & Caribbean Region',
    'Low-income countries': 'Low Income Group',
    'Lower-middle-income countries': 'Lower Middle Income Group',
    'Middle East and North Africa (WB)': 'Middle East & North Africa Region',
    'North America (WB)': 'North America Region',
    'South Asia (WB)': 'South Asia Region',
    'Sub-Saharan Africa (WB)': 'Sub-Saharan Africa Region',
    'Upper-middle-income countries': 'Upper Middle Income Group',
    'World': 'Global',
    'OWID_WRL': 'Global',  # World code
}

# Special cases from your dataset that need to be added
additional_mapping = {
    # From your specific dataset
    'Albania': 'Europe', 'ALB': 'Europe',
    'Algeria': 'Africa', 'DZA': 'Africa',
    'Angola': 'Africa', 'AGO': 'Africa',
    'Antigua and Barbuda': 'Caribbean', 'ATG': 'Caribbean',
    'Armenia': 'Asia', 'ARM': 'Asia',  # Transcontinental, often considered Asia
    'Aruba': 'Caribbean', 'ABW': 'Caribbean',
    'Australia': 'Oceania', 'AUS': 'Oceania',
    'Austria': 'Europe', 'AUT': 'Europe',
    'Azerbaijan': 'Asia', 'AZE': 'Asia',
    'Bahrain': 'Asia', 'BHR': 'Asia',
    'Bangladesh': 'Asia', 'BGD': 'Asia',
    'Belarus': 'Europe', 'BLR': 'Europe',
    'Belgium': 'Europe', 'BEL': 'Europe',
    'Belize': 'Central America', 'BLZ': 'Central America',
    'Benin': 'Africa', 'BEN': 'Africa',
    'Bermuda': 'Caribbean', 'BMU': 'Caribbean',
    'Bhutan': 'Asia', 'BTN': 'Asia',
    'Bolivia': 'South America', 'BOL': 'South America',
    'Bosnia and Herzegovina': 'Europe', 'BIH': 'Europe',
    'Botswana': 'Africa', 'BWA': 'Africa',
    'Brazil': 'South America', 'BRA': 'South America',
    'British Virgin Islands': 'Caribbean', 'VGB': 'Caribbean',
    'Brunei': 'Asia', 'BRN': 'Asia',
    'Bulgaria': 'Europe', 'BGR': 'Europe',
    'Burkina Faso': 'Africa', 'BFA': 'Africa',
    'Burundi': 'Africa', 'BDI': 'Africa',
    'Cambodia': 'Asia', 'KHM': 'Asia',
    'Cameroon': 'Africa', 'CMR': 'Africa',
    'Canada': 'North America', 'CAN': 'North America',
    'Cape Verde': 'Africa', 'CPV': 'Africa',
    'Cayman Islands': 'Caribbean', 'CYM': 'Caribbean',
    'Central African Republic': 'Africa', 'CAF': 'Africa',
    'Chad': 'Africa', 'TCD': 'Africa',
    'Chile': 'South America', 'CHL': 'South America',
    'China': 'Asia', 'CHN': 'Asia',
    'Colombia': 'South America', 'COL': 'South America',
    'Comoros': 'Africa', 'COM': 'Africa',
    'Congo': 'Africa', 'COG': 'Africa',
    'Costa Rica': 'Central America', 'CRI': 'Central America',
    "Cote d'Ivoire": 'Africa', 'CIV': 'Africa',
    'Croatia': 'Europe', 'HRV': 'Europe',
    'Curacao': 'Caribbean', 'CUW': 'Caribbean',
    'Cyprus': 'Europe', 'CYP': 'Europe',  # Geographically Asia, politically Europe
    'Czechia': 'Europe', 'CZE': 'Europe',
    'Democratic Republic of Congo': 'Africa', 'COD': 'Africa',
    'Denmark': 'Europe', 'DNK': 'Europe',
    'Djibouti': 'Africa', 'DJI': 'Africa',
    'Dominica': 'Caribbean', 'DMA': 'Caribbean',
    'Dominican Republic': 'Caribbean', 'DOM': 'Caribbean',
    'Ecuador': 'South America', 'ECU': 'South America',
    'Egypt': 'Africa', 'EGY': 'Africa',
    'Equatorial Guinea': 'Africa', 'GNQ': 'Africa',
    'Estonia': 'Europe', 'EST': 'Europe',
    'Eswatini': 'Africa', 'SWZ': 'Africa',
    'Ethiopia': 'Africa', 'ETH': 'Africa',
    'Fiji': 'Oceania', 'FJI': 'Oceania',
    'Finland': 'Europe', 'FIN': 'Europe',
    'France': 'Europe', 'FRA': 'Europe',
    'Gabon': 'Africa', 'GAB': 'Africa',
    'Gambia': 'Africa', 'GMB': 'Africa',
    'Germany': 'Europe', 'DEU': 'Europe',
    'Ghana': 'Africa', 'GHA': 'Africa',
    'Greece': 'Europe', 'GRC': 'Europe',
    'Grenada': 'Caribbean', 'GRD': 'Caribbean',
    'Guatemala': 'Central America', 'GTM': 'Central America',
    'Guinea': 'Africa', 'GIN': 'Africa',
    'Guinea-Bissau': 'Africa', 'GNB': 'Africa',
    'Honduras': 'Central America', 'HND': 'Central America',
    'Hong Kong': 'Asia', 'HKG': 'Asia',
    'Hungary': 'Europe', 'HUN': 'Europe',
    'Iceland': 'Europe', 'ISL': 'Europe',
    'India': 'Asia', 'IND': 'Asia',
    'Indonesia': 'Asia', 'IDN': 'Asia',
    'Iraq': 'Asia', 'IRQ': 'Asia',
    'Ireland': 'Europe', 'IRL': 'Europe',
    'Israel': 'Asia', 'ISR': 'Asia',
    'Italy': 'Europe', 'ITA': 'Europe',
    'Jamaica': 'Caribbean', 'JAM': 'Caribbean',
    'Japan': 'Asia', 'JPN': 'Asia',
    'Jordan': 'Asia', 'JOR': 'Asia',
    'Kazakhstan': 'Asia', 'KAZ': 'Asia',
    'Kenya': 'Africa', 'KEN': 'Africa',
    'Kuwait': 'Asia', 'KWT': 'Asia',
    'Kyrgyzstan': 'Asia', 'KGZ': 'Asia',
    'Laos': 'Asia', 'LAO': 'Asia',
    'Latvia': 'Europe', 'LVA': 'Europe',
    'Lebanon': 'Asia', 'LBN': 'Asia',
    'Lesotho': 'Africa', 'LSO': 'Africa',
    'Liberia': 'Africa', 'LBR': 'Africa',
    'Lithuania': 'Europe', 'LTU': 'Europe',
    'Luxembourg': 'Europe', 'LUX': 'Europe',
    'Madagascar': 'Africa', 'MDG': 'Africa',
    'Malawi': 'Africa', 'MWI': 'Africa',
    'Malaysia': 'Asia', 'MYS': 'Asia',
    'Maldives': 'Asia', 'MDV': 'Asia',
    'Mali': 'Africa', 'MLI': 'Africa',
    'Malta': 'Europe', 'MLT': 'Europe',
    'Mauritania': 'Africa', 'MRT': 'Africa',
    'Mauritius': 'Africa', 'MUS': 'Africa',
    'Mexico': 'North America', 'MEX': 'North America',
    'Moldova': 'Europe', 'MDA': 'Europe',
    'Mongolia': 'Asia', 'MNG': 'Asia',
    'Montenegro': 'Europe', 'MNE': 'Europe',
    'Morocco': 'Africa', 'MAR': 'Africa',
    'Mozambique': 'Africa', 'MOZ': 'Africa',
    'Namibia': 'Africa', 'NAM': 'Africa',
    'Nepal': 'Asia', 'NPL': 'Asia',
    'Netherlands': 'Europe', 'NLD': 'Europe',
    'New Zealand': 'Oceania', 'NZL': 'Oceania',
    'Nicaragua': 'Central America', 'NIC': 'Central America',
    'Niger': 'Africa', 'NER': 'Africa',
    'Nigeria': 'Africa', 'NGA': 'Africa',
    'North Macedonia': 'Europe', 'MKD': 'Europe',
    'Norway': 'Europe', 'NOR': 'Europe',
    'Oman': 'Asia', 'OMN': 'Asia',
    'Pakistan': 'Asia', 'PAK': 'Asia',
    'Palestine': 'Asia', 'PSE': 'Asia',
    'Panama': 'Central America', 'PAN': 'Central America',
    'Paraguay': 'South America', 'PRY': 'South America',
    'Peru': 'South America', 'PER': 'South America',
    'Philippines': 'Asia', 'PHL': 'Asia',
    'Poland': 'Europe', 'POL': 'Europe',
    'Portugal': 'Europe', 'PRT': 'Europe',
    'Qatar': 'Asia', 'QAT': 'Asia',
    'Romania': 'Europe', 'ROU': 'Europe',
    'Russia': 'Europe/Asia', 'RUS': 'Europe',  # Transcontinental
    'Rwanda': 'Africa', 'RWA': 'Africa',
    'Saint Kitts and Nevis': 'Caribbean', 'KNA': 'Caribbean',
    'Saint Lucia': 'Caribbean', 'LCA': 'Caribbean',
    'Saint Vincent and the Grenadines': 'Caribbean', 'VCT': 'Caribbean',
    'Sao Tome and Principe': 'Africa', 'STP': 'Africa',
    'Saudi Arabia': 'Asia', 'SAU': 'Asia',
    'Senegal': 'Africa', 'SEN': 'Africa',
    'Serbia': 'Europe', 'SRB': 'Europe',
    'Seychelles': 'Africa', 'SYC': 'Africa',
    'Sierra Leone': 'Africa', 'SLE': 'Africa',
    'Singapore': 'Asia', 'SGP': 'Asia',
    'Slovakia': 'Europe', 'SVK': 'Europe',
    'Slovenia': 'Europe', 'SVN': 'Europe',
    'Somalia': 'Africa', 'SOM': 'Africa',
    'South Africa': 'Africa', 'ZAF': 'Africa',
    'South Korea': 'Asia', 'KOR': 'Asia',
    'South Sudan': 'Africa', 'SSD': 'Africa',
    'Spain': 'Europe', 'ESP': 'Europe',
    'Sri Lanka': 'Asia', 'LKA': 'Asia',
    'Sudan': 'Africa', 'SDN': 'Africa',
    'Suriname': 'South America', 'SUR': 'South America',
    'Sweden': 'Europe', 'SWE': 'Europe',
    'Switzerland': 'Europe', 'CHE': 'Europe',
    'Syria': 'Asia', 'SYR': 'Asia',
    'Taiwan': 'Asia', 'TWN': 'Asia',
    'Tajikistan': 'Asia', 'TJK': 'Asia',
    'Tanzania': 'Africa', 'TZA': 'Africa',
    'Thailand': 'Asia', 'THA': 'Asia',
    'Togo': 'Africa', 'TGO': 'Africa',
    'Trinidad and Tobago': 'Caribbean', 'TTO': 'Caribbean',
    'Tunisia': 'Africa', 'TUN': 'Africa',
    'Uganda': 'Africa', 'UGA': 'Africa',
    'United Arab Emirates': 'Asia', 'ARE': 'Asia',
    'United Kingdom': 'Europe', 'GBR': 'Europe',
    'United States': 'North America', 'USA': 'North America',
    'Uruguay': 'South America', 'URY': 'South America',
    'Uzbekistan': 'Asia', 'UZB': 'Asia',
    'Vietnam': 'Asia', 'VNM': 'Asia',
    'Zambia': 'Africa', 'ZMB': 'Africa',
}

# Combine all mappings
full_continent_mapping = {**continent_mapping, **additional_mapping}

# For convenience, create a simplified version with just continents (not sub-regions)
to_drop = [
    'East Asia and Pacific (WB)',
    'Europe and Central Asia (WB)',
    'High-income countries',
    'Latin America and Caribbean (WB)',
    'Low-income countries',
    'Lower-middle-income countries',
    'Middle East and North Africa (WB)',
    'North America (WB)',
    'South Asia (WB)',
    'Sub-Saharan Africa (WB)',
    'Upper-middle-income countries',
    'World'
]
# To use this mapping with your dataframe:
# Option 1: Map by country name
df['continent'] = df['Entity'].map(full_continent_mapping)

# Option 2: Map by country code (for countries that have codes)
df_merged['Region'] = df['Entity'].map(full_continent_mapping)

In [56]:
df_merged = df_merged.loc[df_merged['Entity'] != 'World']

In [57]:
import country_converter as coco

cc = coco.CountryConverter()
df_merged['Region'] = cc.convert(df_merged['Entity'], to='continent', not_found='Unknown')

/var/folders/1s/p455bwm96t543ylvd35wjs5h0000gn/T/ipykernel_1763/2151846884.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged['Region'] = cc.convert(df_merged['Entity'], to='continent', not_found='Unknown')

In [58]:
df_merged.to_csv("data.csv", index=False)

In [59]:
df_obese = df_obese.rename(columns = {'Prevalence of obesity among adults, BMI >= 30 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age':'bmi'})

In [60]:
df

        Entity  Year  Cost of a healthy diet         gdp continent
0      Albania  2017                    3.04  14155.0400    Europe
1      Albania  2018                    3.13  14710.9820    Europe
2      Albania  2019                    3.32  15078.5070    Europe
3      Albania  2020                    3.40  14662.7960    Europe
4      Albania  2021                    3.49  16126.7770    Europe
...        ...   ...                     ...         ...       ...
1357    Zambia  2021                    3.28   3503.0350    Africa
1358    Zambia  2022                    3.61   3585.1238    Africa
1359    Zambia  2023                    3.81   3673.4841    Africa
1360    Zambia  2024                    3.99   3716.0374    Africa
1361  Zimbabwe  2017                    3.54   3453.5059    Africa

[1362 rows x 5 columns]

In [61]:
df_merged = df_merged.merge(df_obese[['Year','Entity','bmi']], on = ['Year','Entity'], how = 'left')

In [62]:
df_merged.isna().sum()

Entity                      0
Year                        0
Cost of a healthy diet      0
gdp                         0
population                  0
Region                      0
bmi                       206
dtype: int64

In [63]:
df_merged.to_csv("data.csv", index=False)

In [64]:
df_food_waste = pd.read_csv('./data/food-waste-per-capita.csv')
#https://ourworldindata.org/grapher/food-waste-per-capita.csv?v=1&csvType=full&useColumnShortNames=true
df_food_waste

FileNotFoundError: [Errno 2] No such file or directory: './data/food-waste-per-capita.csv'

In [ ]:
df_food_waste.describe()

,Year,12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Retail,12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Out-of-home consumption,12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Households
count,552.000000,548.000000,550.000000,550.000000
mean,2020.385870,14.810219,27.517291,82.771436
std,1.825813,9.225359,11.698837,23.947610
min,2008.000000,0.000000,0.000000,0.000000
25%,2019.000000,9.770000,23.472500,70.992500
50%,2021.000000,14.000000,27.270000,84.060000
75%,2022.000000,15.680000,31.140000,92.347500
max,2022.000000,87.940000,88.700000,205.960000

In [ ]:
df_food_waste.isna().sum()

Entity                                                                             0
Code                                                                              34
Year                                                                               0
12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Retail                      4
12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Out-of-home consumption     2
12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Households                  2
dtype: int64

In [ ]:
df_food_waste = df_food_waste.dropna()

In [ ]:
df_food_waste['Year'].unique()

array([2019, 2022, 2020, 2021, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018])

In [ ]:
df_food_waste =df_food_waste[df_food_waste['Year']>=2017]

In [ ]:
df_food_waste.columns

Index(['Entity', 'Code', 'Year',
       '12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Retail',
       '12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Out-of-home consumption',
       '12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Households'],
      dtype='object')

In [ ]:
df_food_waste.rename(columns={'12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Retail':'food_waste_kg_per_capita_retail'}, inplace=True)
df_food_waste.rename(columns={'12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Out-of-home consumption':'food_waste_kg_per_capita_out_of_home'}, inplace=True)
df_food_waste.rename(columns={'12.3.1 - Food waste per capita (KG) - AG_FOOD_WST_PC - Households':'food_waste_kg_per_capita_households'}, inplace=True)
df_food_waste.columns

Index(['Entity', 'Code', 'Year', 'food_waste_kg_per_capita_retail',
       'food_waste_kg_per_capita_out_of_home',
       'food_waste_kg_per_capita_households'],
      dtype='object')

In [ ]:
df_food_waste.describe()

,Year,food_waste_kg_per_capita_retail,food_waste_kg_per_capita_out_of_home,food_waste_kg_per_capita_households
count,505.000000,505.000000,505.000000,505.000000
mean,2020.540594,14.934931,27.158594,83.056297
std,1.433318,9.522418,11.255400,24.308501
min,2017.000000,0.000000,0.000000,0.000000
25%,2019.000000,9.700000,23.830000,71.340000
50%,2021.000000,14.000000,27.230000,84.490000
75%,2022.000000,15.680000,31.140000,92.350000
max,2022.000000,87.940000,87.230000,205.960000

In [ ]:
df_undernourishment = pd.read_csv('./data/prevalence-of-undernourishment.csv')
#https://www.kaggle.com/datasets/whenamancodes/hunger-and-undernourishment-data?resource=download
df_undernourishment.columns

Index(['Entity', 'Code', 'Year',
       'Prevalence of undernourishment (% of population)'],
      dtype='object')

In [ ]:
df_undernourishment.rename(columns={'Prevalence of undernourishment (% of population)':'undernourishment_percent'}, inplace=True)
df_undernourishment.columns

Index(['Entity', 'Code', 'Year', 'undernourishment_percent'], dtype='object')

In [ ]:
df_undernourishment.isna().sum()

Entity                        0
Code                        266
Year                          0
undernourishment_percent      0
dtype: int64

In [ ]:
df_undernourishment['Entity'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada',
       'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
       'East Asia and Pacific', 'Ecuador', 'Egypt', 'El Salvador',
       'Estonia', 'Eswatini', 'Ethiopia', 'Europe and Central Asia',
       'European Union', 'Fiji', 'Finland', 'France', 'French Polynesia',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Guatemala', 'Guyana', 'Haiti', 'High income', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latin America and Caribbean', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Lithuania', 'Low and middle income', 'Low income',
       'Lower middle income', 'Luxembourg', 'Macao', 'Madagascar',
       'Malawi', 'Malaysia', 'Mali', 'Malta', 'Mauritania', 'Mauritius',
       'Mexico', 'Middle East and North Africa', 'Middle income',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Nigeria', 'North America', 'North Korea',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Romania', 'Russia', 'Rwanda',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Slovakia', 'Slovenia', 'Solomon Islands',
       'Somalia', 'South Africa', 'South Asia', 'South Korea', 'Spain',
       'Sri Lanka', 'Sub-Saharan Africa', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Tanzania', 'Thailand', 'Timor', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen'], dtype=object)

In [ ]:
df_undernourishment = df_undernourishment.dropna()

In [ ]:
df_undernourishment['Entity'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada',
       'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guyana',
       'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Lithuania', 'Luxembourg', 'Macao', 'Madagascar',
       'Malawi', 'Malaysia', 'Mali', 'Malta', 'Mauritania', 'Mauritius',
       'Mexico', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Nigeria', 'North Korea',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Romania', 'Russia', 'Rwanda',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Slovakia', 'Slovenia', 'Solomon Islands',
       'Somalia', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Tanzania',
       'Thailand', 'Timor', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen'], dtype=object)

In [ ]:
df_undernourishment = df_undernourishment[df_undernourishment['Entity']!="World"]
df_undernourishment.reset_index(drop=True, inplace=True)

In [ ]:
df_undernourishment

           Entity Code  Year  undernourishment_percent
0     Afghanistan  AFG  2001                 47.799999
1     Afghanistan  AFG  2002                 45.599998
2     Afghanistan  AFG  2003                 40.599998
3     Afghanistan  AFG  2004                 38.000000
4     Afghanistan  AFG  2005                 36.099998
...           ...  ...   ...                       ...
3054        Yemen  YEM  2015                 43.400002
3055        Yemen  YEM  2016                 46.099998
3056        Yemen  YEM  2017                 46.599998
3057        Yemen  YEM  2018                 45.400002
3058        Yemen  YEM  2019                 45.400002

[3059 rows x 4 columns]

In [ ]:
df_undernourishment.Year.unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019])

In [ ]:
df_food_waste.Year.unique()

array([2019, 2022, 2020, 2021, 2017, 2018])

In [ ]:
df_food_waste.isna().sum()

Entity                                  0
Code                                    0
Year                                    0
food_waste_kg_per_capita_retail         0
food_waste_kg_per_capita_out_of_home    0
food_waste_kg_per_capita_households     0
dtype: int64

In [ ]:
df_undernourishment.to_csv("data_undernourishment.csv", index=False)
df_food_waste.to_csv("data_food_waste.csv", index=False)